// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdtlcbsviecgwljvphps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkdGxjYnN2aWVjZ3dsanZwaHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTU4MzcsImV4cCI6MjA2OTMzMTgzN30.uYKOosdp8UQe_HQqzqrjUYFzLTnz5o6YXAkJgYIdnsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});